name: xpoz
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.4.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


executables:
  xpoz: xpoz

assets:
 - public/